<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception; 
ob_start();
session_start();
include("connect.php");

/* Login Control */
if(isset($_POST['login'])){
	$user_mail = htmlspecialchars(trim($_POST['user_mail']));
	$user_pass = htmlspecialchars(trim(sha1(md5($_POST['user_pass']))));

	if($user_mail && $user_pass){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail AND user_pass=:pass");
		$user_qry->execute(array('mail' => $user_mail, 'pass' => $user_pass));
		$count = $user_qry->rowCount();

		if($count==1){
			$_SESSION['user_mail'] = $user_mail;
			header("Location:../home.php");
		}else{
			header("Location:../login.php?status=restrict");
		}
	}
}

/* Remember Password */
if(isset($_POST['repass'])){
	$remail = $_POST['remail'];
	if($remail){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail");
		$user_qry->execute(array('mail'=>$remail));
		$token=$user_qry->fetch(PDO::FETCH_ASSOC);
		$count = $user_qry->rowCount();

		if($count==1){
			$token_code = $token['user_token'];

            require '../phpmailer/Exception.php';
            require '../phpmailer/PHPMailer.php';
            require '../phpmailer/SMTP.php';

            $mail = new PHPMailer();
	
            $mail->isSMTP();
            $mail->Host = 'excessreklam.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'no-reply@excessreklam.com'; //paste one generated by Mailtrap
            $mail->Password = '9875321Loid'; //paste one generated by Mailtrap
            $mail->SMTPSecure = 'ssl';
            $mail->Port = 465;
            $mail->From     = "no-reply@excessreklam.com";
            $mail->Fromname = "Şifre Sıfırlama Talebi";
            $mail->CharSet = 'UTF-8';
            $mail->AddAddress($token['user_mail']);
            $mail->Subject  = "Şifre Sıfırlama Talebi";
            $mail->isHTML(true);
            $mail->Body = '<html>
                        <head>
                        <title>Şifre Sıfırlama</title>
                        </head>
                        <body>
                            <p style="font-weight: bold;">Talebiniz üzerine şifre sıfırlama linki aşağıda belirtilmiştir. Linke tıklayarak yeni şifrenizi belirleyeceğiniz sayfaya gidebilirisiniz.</p>
                            <p><a href="https://www.excessreklam.com/admin/newpass.php?renewpass=true&token='.$token_code.'">Şifreyi Sıfırla</a></p>
                        </body>
                        </html>';
            
            $mail->IsHTML(true);


            if($mail->Send())
            {
                header('Location:../login.php?status=mailsent');
            }
            else {
                    header('Location:../login.php?status=mailsentfail');
            }

		}else{
			header('Location:../login.php?status=repassfail');
		}
	}
}

/* Renew Password */
if(isset($_POST['newpass'])){
	$token = $_POST['user_token'];
	if($_POST['pass']!== $_POST['pass_control']){
		header("Location:../newpass.php?token=$token&status=notequal");
	}else{
	$query=$db->prepare("UPDATE users SET
	user_pass=:pass,
	user_token=:token WHERE user_id={$_POST['user_id']}");
	$update=$query->execute(array(
	'pass'=>sha1(md5($_POST['pass_control'])),
	'token'=>md5(uniqid())
	));

	if($update){
		header('Location:../login.php?status=passchanged');
	}else{
		header('Location:../login.php?status=passchangefail');
	}
	}
}

/* Profile Picture Update */
if(isset($_POST['picupdate'])){
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['user_pic']['name'],strpos($_FILES['user_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Sadece JPG, PNG ve GIF formatı yükleyebilirsiniz.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

	if($_FILES['user_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemeye çalıştığınız resim en fazla 1mb. boyutunda olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

		$uploads_dir='../img';
		@$tmp_name=$_FILES['user_pic']["tmp_name"];
		@$name=$_FILES['user_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,3)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$update_prof=$db->prepare("UPDATE users SET
		user_pic=:pic
		WHERE id={$_POST['user_id']}");

		$update=$update_prof->execute(array(
		'pic'    =>$refimgyol));

		if($update){
			$unlink=$_POST['unlink'];
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Profil resmi başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			unlink("../$unlink");
			header("Location:../profilesetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Profil resmi güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../profilesetup.php");
		}
}

/* Add Slider */
if(isset($_POST['add_slider'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['slider_pic']['name'],strpos($_FILES['slider_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-slider.php');
		exit();
	}
	if($_FILES['slider_pic']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-slider.php');
		exit();
	}else{
		$uploads_dir='../../images/slider';
		@$tmp_name=$_FILES['slider_pic']["tmp_name"];
		@$name=$_FILES['slider_pic']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$add_image=$db->prepare("INSERT INTO slider SET
		title_tr=:title_tr,
		title_en=:title_en,
		text_tr=:text_tr,
		text_en=:text_en,
		pic_url=:pic");

		$add_service=$add_image->execute(array(
		"title_tr" => trim($_POST["title_tr"]),
		"title_en" => trim($_POST["title_en"]),
		"text_tr"  => trim($_POST["text_tr"]),
		"text_en"  => trim($_POST["text_en"]),
		'pic'      => $refimgyol));

		if($add_service){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Slider başarılı bir şekilde eklenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../sliderlist.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Slider eklenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header('Location:../sliderlist.php');
		}
	}
}

/* Slider Rank */
if(isset($_POST["data"])){
	parse_str($_POST["data"], $siralama);
	$rank = $siralama["rank"];
	foreach($rank as $key => $id){
		
		$query=$db->prepare("UPDATE slider SET slider_rank=:rank WHERE id=:id");
		$update=$query->execute(array("rank" => $key, "id" => $id));
	}
}

/* Slider Picture Update */
if(isset($_POST['update_slider_pic'])){
	
	$slider_id=$_POST['slider_id'];
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['slider_pic']['name'],strpos($_FILES['slider_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
		exit();
	}
	if($_FILES['slider_pic']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
		exit();
	}else{
		$uploads_dir='../../images/slider';
		@$tmp_name=$_FILES['slider_pic']["tmp_name"];
		@$name=$_FILES['slider_pic']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_slider_pic=$db->prepare("UPDATE slider SET
		pic_url=:pic WHERE id={$slider_id}");

		$updated=$edit_slider_pic->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["slider_pic"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Slider resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../edit-slider.php?id=$slider_id");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Slider resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../edit-slider.php?id=$slider_id");
		}
	}
}

/* Slider Content Update */
if(isset($_POST['edit_slider'])){
	
	$slider_id=$_POST['slider_id'];
	
	$edit_slider=$db->prepare("UPDATE slider SET
	title_tr=:title_tr,
	title_en=:title_en,
	text_tr=:text_tr,
	text_en=:text_en WHERE id={$slider_id}");

	$updated=$edit_slider->execute(array(
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"text_tr"   => trim($_POST["text_tr"]),
	"text_en"   => trim($_POST["text_en"])));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Hizmet başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../edit-slider.php?id=$slider_id");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
	}
}

/* Delete Slider */
if(isset($_POST["delete_slider"])){
	$delete_qry=$db->prepare("DELETE FROM slider WHERE id=:id");
	$delete_slider=$delete_qry->execute(array('id'=>$_POST['delete_id']));
	if($delete_slider){
		$unlink=$_POST["unlink"];
		unlink("../../$unlink");
	}
}
?>