<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception; 
ob_start();
session_start();
include("connect.php");

/* Login Control */
if(isset($_POST['login'])){
	$user_mail = htmlspecialchars(trim($_POST['user_mail']));
	$user_pass = htmlspecialchars(trim(sha1(md5($_POST['user_pass']))));

	if($user_mail && $user_pass){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail AND user_pass=:pass");
		$user_qry->execute(array('mail' => $user_mail, 'pass' => $user_pass));
		$count = $user_qry->rowCount();

		if($count==1){
			$_SESSION['user_mail'] = $user_mail;
			header("Location:../home.php");
		}else{
			header("Location:../login.php?status=restrict");
		}
	}
}

/* Remember Password */
if(isset($_POST['repass'])){
	$remail = $_POST['remail'];
	if($remail){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail");
		$user_qry->execute(array('mail'=>$remail));
		$token=$user_qry->fetch(PDO::FETCH_ASSOC);
		$count = $user_qry->rowCount();

		if($count==1){
			$token_code = $token['user_token'];

            require '../phpmailer/Exception.php';
            require '../phpmailer/PHPMailer.php';
            require '../phpmailer/SMTP.php';

            $mail = new PHPMailer();
	
            $mail->isSMTP();
            $mail->Host = 'excessreklam.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'no-reply@excessreklam.com'; //paste one generated by Mailtrap
            $mail->Password = '9875321Loid'; //paste one generated by Mailtrap
            $mail->SMTPSecure = 'ssl';
            $mail->Port = 465;
            $mail->From     = "no-reply@excessreklam.com";
            $mail->Fromname = "Şifre Sıfırlama Talebi";
            $mail->CharSet = 'UTF-8';
            $mail->AddAddress($token['user_mail']);
            $mail->Subject  = "Şifre Sıfırlama Talebi";
            $mail->isHTML(true);
            $mail->Body = '<html>
                        <head>
                        <title>Şifre Sıfırlama</title>
                        </head>
                        <body>
                            <p style="font-weight: bold;">Talebiniz üzerine şifre sıfırlama linki aşağıda belirtilmiştir. Linke tıklayarak yeni şifrenizi belirleyeceğiniz sayfaya gidebilirisiniz.</p>
                            <p><a href="https://www.excessreklam.com/admin/newpass.php?renewpass=true&token='.$token_code.'">Şifreyi Sıfırla</a></p>
                        </body>
                        </html>';
            
            $mail->IsHTML(true);


            if($mail->Send())
            {
                header('Location:../login.php?status=mailsent');
            }
            else {
                    header('Location:../login.php?status=mailsentfail');
            }

		}else{
			header('Location:../login.php?status=repassfail');
		}
	}
}

/* Renew Password */
if(isset($_POST['newpass'])){
	$token = $_POST['user_token'];
	if($_POST['pass']!== $_POST['pass_control']){
		header("Location:../newpass.php?token=$token&status=notequal");
	}else{
	$query=$db->prepare("UPDATE users SET
	user_pass=:pass,
	user_token=:token WHERE user_id={$_POST['user_id']}");
	$update=$query->execute(array(
	'pass'=>sha1(md5($_POST['pass_control'])),
	'token'=>md5(uniqid())
	));

	if($update){
		header('Location:../login.php?status=passchanged');
	}else{
		header('Location:../login.php?status=passchangefail');
	}
	}
}

/* Profile Picture Update */
if(isset($_POST['picupdate'])){
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['user_pic']['name'],strpos($_FILES['user_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Sadece JPG, PNG ve GIF formatı yükleyebilirsiniz.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

	if($_FILES['user_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemeye çalıştığınız resim en fazla 1mb. boyutunda olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

		$uploads_dir='../img';
		@$tmp_name=$_FILES['user_pic']["tmp_name"];
		@$name=$_FILES['user_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,3)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$update_prof=$db->prepare("UPDATE users SET
		user_pic=:pic
		WHERE user_id={$_POST['user_id']}");

		$update=$update_prof->execute(array(
		'pic'    =>$refimgyol));

		if($update){
			$unlink=$_POST['unlink'];
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Profil resmi başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			unlink("../$unlink");
			header("Location:../profilesetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Profil resmi güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../profilesetup.php");
		}
}
?>